name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use your Node.js version

      - name: Install Dependencies
        run: |
          npm install
          npm run build  # Build your application

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Sync build files to EC2 instance
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./build/ "$REMOTE_USER@$REMOTE_HOST:$TARGET"

          # Restart the web server (assuming Node.js)
          ssh -o StrictHostKeyChecking=no "$REMOTE_USER@$REMOTE_HOST" << 'EOF'
            pm2 stop all || true   # Stops the server if running
            pm2 start $TARGET/app.js  # Replace with your entry file if needed
            pm2 save                 # Saves the process list for future reboots
          EOF
